<?php

namespace AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use AppBundle\Document\Photo;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * AttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends DocumentRepository
{
    public function getThumbnail($photoid)
    {
        return $this->createQueryBuilder()
                    ->readOnly()
                    ->select('thumbnail')
                    ->field('_id')->equals($photoid)
                    ->getQuery()
                    ->getSingleResult();
    }

    public function getImage($photoid)
    {
        return $this->createQueryBuilder()
                    ->readOnly()
                    ->select('base64', 'ext', 'imageSize')
                    ->field('_id')->equals($photoid)
                    ->getQuery()
                    ->getSingleResult();
    }
}
