imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']

doctrine_mongodb:
    connections:
        default:
            server: '%database_host%:%database_port%'
            options: {}
    default_database: '%database_name%'
    document_managers:
        default:
            auto_mapping: true

vich_uploader:
    db_driver: mongodb
    mappings:
        attachement_image:
            uri_prefix: /photos
            upload_destination: '%kernel.root_dir%/../var/cache/upload'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: false
            delete_on_remove: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# @see https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/576
sensio_framework_extra:
    router:
        annotations: false
